UCSCLibrary/ucsc-library-digital-collections

app/assets/stylesheets/ucsc.scss
app/indexers/work_indexer.rb
app/views/hyrax/base/_metadata.html.erb
app/views/hyrax/base/_relationships.html.erb
app/views/hyrax/base/_relationships_parent_row.html.erb
app/views/hyrax/base/_relationships_parent_rows.html.erb
app/views/hyrax/base/show.html.erb
config/locales/hyrax.en.yml

Resolves [](https://github.com/UCSCLibrary/dams_project_mgmt/issues/130)
- Updates site CSS for metadata header, tables, and buttons.
- Moves rendering of relationships from show.html.erb to metadata.html.erb.
- Removes bootstrap table classes from the metadata table element.
- Changes 'More information' from button element to span+a elements.
- Renders relationships as table elements rather than definition lists.
- Customizes the label for Admin Set to remove the 
extra colon.

130 Implement new metadata display

---

app/controllers/application_controller.rb

This is the last step in implementing image authorization for our IIIF image server

provide an access token for our image server as a cookie to all visitors

---

app/views/hyrax/base/show.html.erb

Resolves [218 - Mobile links bug](https://github.com/UCSCLibrary/dams_project_mgmt/issues/218)
Changes:
- Corrected the bootstrap layout classes and added a missing row div.

Detail links now work on mobile browsers, by fixing bootstrap layout classes

---

app/views/catalog/_targeted_search_form.html.erb

Resolves [#261 DAMS Field Select Box Needs Description](https://github.com/UCSCLibrary/dams_project_mgmt/issues/261).
Changes: Adds an Aria-label attribute to the select dropdown for "search field" on the main search form.
No relevant screenshots - this is for screen readers.

Aria label added to search form field.

---

app/assets/stylesheets/ucsc.scss.erb
app/controllers/collections_controller.rb
app/presenters/ucsc/collection_presenter.rb
app/views/hyrax/collections/_collection_description.html.erb
app/views/hyrax/collections/show.html.erb

Resolves [#222 collection description box](https://github.com/UCSCLibrary/dams_project_mgmt/issues/222)
- Extends Hyrax collection presenter with the UCSC version.
- Adds a related_resource method to the UCSC collection presenter.
- Customizes the collection description partial to add a link to the guide.
- Styles the page with bootstrap classes and a bit of custom css.

Implement collection landing page description box.

---

app/assets/stylesheets/ucsc.scss.erb

Resolves [369 Landing page thumbnail issue](https://github.com/UCSCLibrary/dams_project_mgmt/issues/369)
Changes:
- Removes css line that caused the skewing.
Screenshot:

Resolves 369, thumbnails no longer skewed.

---

app/assets/stylesheets/ucsc.scss.erb

Resolves [380 Hide list, masonry and slideshow browse views](https://github.com/UCSCLibrary/dams_project_mgmt/issues/380) and partially resolves [371 Remove thumbnail view options](https://github.com/UCSCLibrary/dams_project_mgmt/issues/371)
Using CSS, hides the view-type element on collection landing pages and search results pages.

Hide view options on collection landing page and search results pages.

---

app/assets/javascripts/tooltips.js
app/assets/stylesheets/ucsc.scss.erb
app/views/catalog/_index_gallery.html.erb
app/views/catalog/_index_header_gallery_default.html.erb

Resolves [249 - Style Titles for Search Results](https://github.com/UCSCLibrary/dams_project_mgmt/issues/249).
Code changes:
- New js file to enable bootstrap tooltips. app/assets/javascripts/tooltips.js 
- New view partial to customize Blacklight gallery by adding tooltips.  app/views/catalog/_index_gallery.html.erb 
- Update app/views/catalog/_index_header_gallery_default.html.erb to truncate title and add tooltip.
- CSS styling for tooltips.
Screenshot:

Style titles for search results pages

---

app/assets/stylesheets/ucsc.scss.erb
app/builders/hyrax/bootstrap_breadcrumbs_builder.rb
app/builders/ucsc/bootstrap_breadcrumbs_builder.rb
app/views/layouts/hyrax.html.erb
app/views/layouts/hyrax/dashboard.html.erb
lib/ucsc/breadcrumbs_for_works.rb

Resolves [40 - Apply new breacrumb style](https://github.com/UCSCLibrary/dams_project_mgmt/issues/40).
Code changes:
- Customizes app/builders/hyrax/bootstrap_breadcrumbs_builder.rb, removes truncate function
- Adds root path breadcrumb to lib/ucsc/breadcrumbs_for_works.rb 
- A few CSS styling rules
Screenshot:

Breadcrumb style

---

app/assets/javascripts/citations.js
app/assets/javascripts/embed.js
app/assets/javascripts/facets.js
app/assets/javascripts/homepage.js
app/assets/javascripts/tooltips.js

Resolves [423 - View all collections button doesn't work if someone uses the "browse collections link"](https://github.com/UCSCLibrary/dams_project_mgmt/issues/423).
Traced this one back to the document.ready function. This function doesn't fire when turbolinks loads the page, and so all instances of $(document).ready have been replaced with the $(document).on('turbolinks:load') instead.

Javascript bug fix

---

stack_car/.env

Setting the ENV variable for image_token_secret resolves several rspec failing tests.

ENV variable for image_server

---

app/indexers/collection_indexer.rb

Do not override indexing of controlled fields - they get indexed by `#index_controlled_fields`
Fixes `spec/models/collection_spec.rb`

Fix indexed controlled fields

---

app/indexers/controlled_indexer_behavior.rb

`#gsub!` returns nil, nulling the `cleaned_url` variable 
This fixes the `spec/indexers/work_indexer_spec.rb`

Fix fetching remote labels

---

app/factories/bulkrax/object_factory.rb
app/indexers/controlled_indexer_behavior.rb
app/models/concerns/bulkrax/has_local_processing.rb

---
Ref https://gitlab.com/notch8/ucsc-library-digital-collections/-/issues/29 
- E.g. when importing `http://www.geonames.org/5393052` into `subjectPlace`, [the show page should display "Santa Cruz"](https://share.getcloudapp.com/DOu6YONo) 
1. Download this CSV of sample data: [Object Types - Ingest Spreadsheet.csv](https://github.com/UCSCLibrary/ucsc-library-digital-collections/files/7771466/Object.Types.-.Ingest.Spreadsheet.csv)  
2. Login to [staging](http://ucsc-hyrax-staging.notch8.cloud) as an admin<sup>1</sup>. Navigate to Dashboard > Importers 
3. Click the New button. Fill out all the required fields. Upload the CSV from Step 1. Click "Create and Import" 
4. Locate one of the newly imported works.<sup>2</sup> Navigate to the work's public-facing show page 
5. Validate that the …

i29 Add support for importing controlled fields with Bulkrax

---

lib/capistrano/tasks/link-stream.rake

On the sandbox server, imports keep failing with the following error: 
```
Errno::ENOENT: No such file or directory @ rb_sysopen - tmp/imports/8_20220126211059/OT_simple.csv
```
even though the mentioned file exists at the correct location. This seems to be because Sidekiq is running on a separate "ingest" server, which does not have access to the files uploaded by Bulkrax. 
On deploy, symlink required bulkrax tmp directories to shared directory so it can be accessed by the ingest server

Symlink Bulkrax tmp/ directories to shared directory

---

lib/capistrano/tasks/link-stream.rake

On the sandbox server, `/dams_derivatives/tmp/sandbox/` is missing both `import/` and `export/` directories. We need to ensure they get created on deploy

ensure shared directories exist before symlinking

---

app/indexers/sortable_field_indexer_behavior.rb
app/models/concerns/bulkrax/has_local_processing.rb

The source of this bug ended up being in a custom parser, not Bulkrax. This PR includes some cleanup in the `HasLocalProcessing` concern for legibility

Bulkrax - do not raise `Date.parse` error when importing blank `dateCreated` values

---

app/views/bulkrax/importers/_browse_everything.html.erb
app/views/hyrax/base/_form_files.html.erb
app/views/shared/_browse_everything_button.erb

Add BrowseEverything button partial with custom JS; override Hyrax and Bulkrax views to use custom BE button. 
With this change, Cloud Files are functional when using Bulkrax to import records. However, using BE through the UI does not set up files correctly (although it still fixes the problem where the modal never closes)

Fix BrowseEverything modal JS bug

---

Gemfile
Gemfile.lock
db/schema.rb

Bump Bulkrax version to ~> 2.3. This resolves the following [bug](https://github.com/samvera-labs/bulkrax/issues/417): 
> If a Collection entry fails during Import, it halts the processing of all following Collection entries
Closes https://github.com/UCSCLibrary/dams_project_mgmt/issues/502

Bulkrax - collection creation bug fix

---

app/models/concerns/bulkrax/has_local_processing.rb
spec/factories/bulkrax_entries.rb
spec/factories/bulkrax_importers.rb
spec/models/concerns/has_local_processing_spec.rb

Resolves https://github.com/UCSCLibrary/dams_project_mgmt/issues/499 
- Do not fill in blank rights statements
- Only fill in blank rights statements if selecting "Override rights statements" on the importer 
- Condense rights statement overrides 
- Specs 
- Bring over a couple spec factories from Bulkrax

i499 Do not fill in blank rights statements when importing

---

app/models/concerns/hyrax/basic_metadata.rb
config/metadata.yml
spec/models/collection_spec.rb
spec/models/work_spec.rb

Ref https://github.com/UCSCLibrary/dams_project_mgmt/issues/498 
- Add `dateCreatedIngest` property 
- Update predicates to match updates in the [data dictionary](https://docs.google.com/spreadsheets/d/1q2xrxULg6whSHYxXeirz7KnghEb_xCMPvW6x_wdo9aU/edit#gid=1359124498) 
- Specs for predicates

i498 Add dateCreatedIngest property, update predicates

---

app/forms/hyrax/work_form.rb
app/indexers/sortable_field_indexer_behavior.rb
app/models/concerns/bulkrax/has_local_processing.rb
app/views/hyrax/base/_secondary_attribute_rows.html.erb
config/initializers/bulkrax.rb
spec/models/concerns/has_local_processing_spec.rb

Ref https://github.com/UCSCLibrary/dams_project_mgmt/issues/498

i498 Use dateCreatedIngest to index dateCreated

---

app/models/collection.rb
app/models/concerns/hyrax/basic_metadata.rb

[ScoobySnacks::WorkModelBehavior](https://github.com/UCSCLibrary/ScoobySnacks/blob/master/lib/scooby_snacks/work_model_behavior.rb#L23) calls `#accepts_nested_attributes_for`, which finalizes the metadata schema, which causes two issues: 
1. All properties added after `include ScoobySnacks::WorkModelBehavior` will throw `UndefinedPropertyError`s 
2. `Hyrax::BasicMetadata` _also_ calls `#accepts_nested_attributes_for`, leading to a conflict 
Instead of fixing the bug in ScoobySnacks, I opted to fix it in this repo since we'll need to bring the change over anyways once the ScoobySnacks gem is removed from the project

Fix ActiveTriples::UndefinedPropertyError for Collection properties

---

app/indexers/controlled_indexer_behavior.rb

Ref https://github.com/UCSCLibrary/dams_project_mgmt/issues/513 
Local authorities are indexed on unique URIs, so only call `#find_or_create_by!` on the URI

Fix RecordNotUnique error when minting local authorities

---

stack_car/Dockerfile

The firefox and geckodriver on Dockerfile are outdated, causing the jenkins build to fail.

update firefox and gecko driver to latest versions

---

app/controllers/catalog_controller.rb
app/models/concerns/hyrax/basic_metadata.rb
app/presenters/ucsc/work_show_presenter.rb
app/views/hyrax/base/_attribute_rows.html.erb
config/initializers/bulkrax.rb
config/metadata.yml

-Adds `descriptionNeighborhood` to bulkrax imports&exports
- `descriptionNeighborhood `can now be exported with bulkrax
- `descriptionNeighborhood` can now be imported with bulkrax and display on the workshow page
- the label for `desciptionNeighborhood` is 'Neighborhood'
https://github.com/UCSCLibrary/dams_project_mgmt/issues/528
- Show page: 
- Export:
- Import:

528 description neighborhood import/export/display

---

app/models/concerns/bulkrax/has_local_processing.rb

Rights statement was not being imported due to a local override that was no longer needed. This PR removes that line and enables `rightsStatement` to be imported & show up on the work show page
- Parsed metadata:
- Work show page:
- Exported csv:

524 Rights statement import export

---

Gemfile
Gemfile.lock

Bulkrax release notes: https://github.com/samvera-labs/bulkrax/releases/tag/v3.0.0.beta8 
Related issue: https://github.com/UCSCLibrary/dams_project_mgmt/issues/537

update Bulkrax to v3.0.0.beta8

---

Gemfile
Gemfile.lock
app/factories/bulkrax/object_factory.rb

- Upgrade to Bulkrax 3.0.1 🎉 
- [v3.0.0 Release Notes](https://github.com/samvera-labs/bulkrax/releases/tag/v3.0.0) 
- [v3.0.0 Release Notes](https://github.com/samvera-labs/bulkrax/releases/tag/v3.0.1) 
- Fix `ActiveFedora unknown attribute "member_of_collections_attributes"` error when importing child collections
- See https://github.com/samvera-labs/bulkrax/pull/508

Bulkrax v3 release-related updates

---

app/models/concerns/bulkrax/has_local_processing.rb

Related: https://github.com/UCSCLibrary/dams_project_mgmt/issues/519 
Changes: 
- remove fuzzy search
- only return search result if the authority label matches the imported value

i519 Local authority should mint on exact match only

---

config/metadata.yml

Ref https://github.com/UCSCLibrary/dams_project_mgmt/issues/517 
Remove `data_type: date` metadata schema config for `dateDigitized` and `datePublished` fields, which were [recently converted from date fields into string fields](https://github.com/UCSCLibrary/ucsc-library-digital-collections/commit/dacede13242d5bf14e6ff330b85bf07dfa928f55).

i517 Fix dateDigitized and datePublished UI error

---

Gemfile.lock
app/jobs/bulkrax/create_relationships_job.rb
app/jobs/inherit_metadata_job.rb

Ref https://github.com/UCSCLibrary/dams_project_mgmt/issues/518 
Changes: 
- Update Bulkrax to v3.2.0 ([release notes](https://github.com/samvera-labs/bulkrax/releases/tag/v3.2.0)) 
- Trigger new `InheritMetadataJob` after `Bulkrax::CreateRelationshipsJob` finishes creating relationships

i518 trigger work metadata inheritance after relationships are imported

---

app/models/concerns/bulkrax/has_local_processing.rb
spec/models/concerns/has_local_processing_spec.rb

Ref https://github.com/UCSCLibrary/dams_project_mgmt/issues/518 
When processing controlled fields on ingest, remove trailing slashes and the "s" from "https" in user-provided URI values

i518 Sanitize controlled field URI values

---

app/actors/hyrax/actors/create_with_files_actor.rb

Ref https://github.com/UCSCLibrary/dams_project_mgmt/issues/542 
Override Hyrax actor to filter out ScoobySnacks attrs that cause errors. 
This error occurs when importing a work using Bulkrax that meets the following criteria: 
- Imports at least one controlled field 
- Has a filename in the `filename` column

i542 Fix ActiveJob::SerializationError when importing ScoobySnacks controlled fields

---

app/assets/stylesheets/ucsc.scss.erb

Resolved #420 (hopefully)
- New CSS rules apply a max height to A-Z thumbnails, and fit to cover the 100x100 space.

Make A-Z collection thumbnails same size with css.

---

app/assets/stylesheets/ucsc.scss.erb

Resolves #375 by hiding collection descriptions and adjusting the spacing of the title in relation to the thumbnail

Hide collection descriptions on mobile a-z collections page.

---

app/controllers/collections_controller.rb
app/views/hyrax/collections/show_all.html.erb

Resolves #382. This PR should be considered to also include [the previous commit](https://github.com/UCSCLibrary/ucsc-library-digital-collections/commit/f58cbffd7a72bb29d62c16a371aaedd6ade2b913) erroneously made to sandbox branch.
Adds visibility filtering back to the A-Z collections page.
It's unclear from testing so far whether or not this is working. From dashboard, if you edit a collection and click the Discovery tab you can set the visibility to "UC Santa Cruz". Then viewing the collection in the dashboard will show its visibility set to "UC Santa Cruz". I haven't been able to find any code responsible for the "UC Santa Cruz" value for visibility, and don't know what its machine name might be.
However, looking at the collections that are currently on production and sandbox and …

Add visibilty filtering back to A-Z list.

---

app/controllers/catalog_controller.rb

Resolves #367 by removing the relevant sort options from app/controllers/catalog_controller.rb.

Remove date uploaded and modified from sort options.

---

README.md

Resolves #388 making the README up-to-date by removing N8 references and adding in stack-car instructions and a brief description of our current development workflow.

README remove N8 and add stack-car instructions.

---

config/metadata.yml

Fixes #523 
Makes description full-text searchable, but requires a SOLR re-index for this change to take effect.

Fix typo in config/metadata.yml

---

app/models/work.rb

The id check is not necessary here. Inhertance for all fields work the same if no child value is present.

remove controlled field check, all inheritance works same

---

config/locales/en.yml

Fixes #559 by adding string translations to locales/en.yml instead of relying on hyrax default translations.

Add missing translations to en.yml

---

app/indexers/controlled_indexer_behavior.rb
app/models/concerns/bulkrax/has_local_processing.rb
config/metadata.yml

Resolves #570.
Changes:
1. When indexing labels, purl.org URI's are parsed to grab the label from the end.
2. When importing with bulkrax, purl.org URI's are changed to use local vocabulary instead.
3. Work edit form now uses textbox_autosuggest for ResourceType instead of dropdown.

ResourceType uses local vocab instead of purl.org

---

app/assets/stylesheets/ucsc.scss.erb
app/views/hyrax/base/_metadata.html.erb

Resolves #598.
- Adds javascript to reset the metadata presentation when the browser is resized, ensuring the mobile presentation or the desktop presentation displays as appropriate.
- Uses a debouncer function to prevent the browser resize happening too quickly/spastically on some browsers.
- Removes the css that was a previous attempt to handle this.

Add javascript to handle item-set metadata when browser is resized.

---

app/models/concerns/bulkrax/has_local_processing.rb

A fix for #570.
- Bulkrax local processing converts purl.org URI's into local vocabulary URI's
- Bulkrax URI sanitizing for local vocabs now checks for the term before proceeding, creating a new term if necessary.

Mint local type when purl.org is used and local type doesn't yet exist

---

app/views/_ga.html.erb
config/initializers/hyrax.rb

Resolves #608.
- Changes the Google Analytics ID in hyrax configuration to our new GA4 tag.
- Overwrites Hyrax's _ga.html.erb partial to use the new gtag script instead of the legacy ga.js.
- Manually adds our old UA tag to the partial to ensure data continuity.

608 google analytics

---

config/environments/production.rb
config/environments/sandbox.rb
config/environments/staging.rb

Resolves #404 
Adds `config.i18n.available_locales = [:en]` in the application config. Standardizes the internationalization configuration across sandbox, staging, and production.

Available locales includes only English

---

app/presenters/ucsc/work_show_presenter.rb

Resolves #652 by changing the default from 800 to 1000 in the work presenter. This is a temporary stop-gap to deal with the 800px derivatives sometimes having missing pieces.

Image size now 1000 default on work show page

---

config/environments/production.rb
config/environments/sandbox.rb
config/environments/staging.rb
config/initializers/locales.rb
public/500.html

Resolves #404
1. Our desired configuration for Rails I18n gem is consistent across environments, so the config setup moved from environment specific files into its own file under config/initializers.
2. The error page for unsupported languages (and all other 500 errors) now has friendlier language and link back to the homepage.

404 translations

---

stack_car/run-tests-when-ready.sh

Fixes these errors in jenkins deployment:
```
stack_car/run-tests-when-ready.sh: line 7: wait-for-services.sh: command not found
stack_car/run-tests-when-ready.sh: line 11: wait-for-services.sh: command not found
stack_car/run-tests-when-ready.sh: line 12: wait-for-services.sh: command not found
stack_car/run-tests-when-ready.sh: line 13: wait-for-services.sh: command not found
```

Fix deploy wait script

---

Jenkinsfile
stack_car/docker-compose.yml

1. Adds the application volume back to docker-compose to enable development without rebuilds.
2. Fixes the permissions issues in deployment by manually updating them in the Jenkinsfile.
3. Breaks shell commands into multiple lines for easier reading.
4. Removes branch variable from most commands now that docker-compose no longer requires it.

Fix permissions issues in deployment pipeline.

---

app/indexers/file_set_indexer.rb
app/indexers/work_indexer.rb
app/indexers/work_type_indexer_behavior.rb
app/models/solr_document.rb

Resolves #656.
- Indexes audio? and image? methods to improve performance on search results, collection landing pages, and work show pages.
- Leaves legacy methods for those values to preserve functionality while re-indexing is incomplete.
To see the performance improvements, we will need to re-index the site. After that is completed the legacy methods can be removed.

Index audio? and image? methods to improve performance

---

app/indexers/sortable_field_indexer_behavior.rb

Resolves #675 by adding a regex match on YYYY-YYYY formats. This allows for re-indexing works with this legacy format in one or more of their fields. I also added some comments about the regex, so future me can avoid reading regex.

Index YYYY-YYYY date formats. Add comments.
