UCSCLibrary/ucsc-library-digital-collections

- app/assets/stylesheets/ucsc.scss
- app/views/hyrax/base/_primary_media.html.erb
- app/views/hyrax/base/show.html.erb
For https://github.com/UCSCLibrary/dams_project_mgmt/issues/135
Updated app/views/hyrax/base/show.html.erb and app/views/hyrax/base/_primary_media.html.erb to add html for css identifiers and a couple glyphicon span elements.
Updated app/assets/stylesheets/ucsc.css to style the image display.
> Issue 135, redesign single image.

- app/assets/stylesheets/ucsc.scss
- app/views/hyrax/base/_primary_media.html.erb
- app/views/hyrax/base/show.html.erb
Reverts UCSCLibrary/ucsc-library-digital-collections#99
I just realized that this pull went directly to the master branch. I believe it should be merged and deployed in staging first according to our workflow. I am reverting the master branch to before this pull was merged, and then I'll try to apply it to staging. 
In the future, I think it's possible to specify which branch to merge into when you're creating a pull request. 
Cheers!
> Revert "Issue 135, redesign single image."

- config/initializers/session_store.rb
This resolves [https://github.com/UCSCLibrary/dams_project_mgmt/issues/155](https://github.com/UCSCLibrary/dams_project_mgmt/issues/155)
> expose cookies to a slightly wider domain, so image server can read them

- app/controllers/ucsc/authorization_controller.rb
- config/routes.rb
This is the simplest implementation of the functionality required by issue 157 in the dams project management repository.
The performance needs to be evaluated before this is deployed in production, and deploying the current code in staging will help me perform that validation.
> add simple endpoint for authorization

- lib/tasks/development_seed.rake
Adding a seed file to automatically populate a hycruz instance with some example records.
> add draft seed task

- app/views/shared/_ajax_modal.html.erb
Resolves [260 Invalid aria attribute in blacklight modal](https://github.com/UCSCLibrary/dams_project_mgmt/issues/260).
Overrides blacklight partial at app/views/shared/_modal.html.erb with solution from https://github.com/projectblacklight/blacklight/commit/c569c2cf8743bfc2ac1453685b8fae7954034415
> Fixes accessibility issue in Blacklight (Project blacklight issue 1776).

- app/assets/stylesheets/ucsc.scss
- app/views/hyrax/collections/_facets.html.erb
- app/views/hyrax/collections/_paginate.html.erb
- app/views/hyrax/collections/_sort_and_per_page.html.erb
- app/views/hyrax/collections/show.html.erb
- app/views/kaminari/ucsc/_first_page.html.erb
- app/views/kaminari/ucsc/_gap.html.erb
- app/views/kaminari/ucsc/_last_page.html.erb
- app/views/kaminari/ucsc/_next_page.html.erb
- app/views/kaminari/ucsc/_page.html.erb
- app/views/kaminari/ucsc/_paginator.html.erb
- app/views/kaminari/ucsc/_prev_page.html.erb
- config/locales/hyrax.en.yml
Resolves [Collection landing page: Desktop](https://github.com/UCSCLibrary/dams_project_mgmt/issues/176) and [Collection landing page: Mobile](https://github.com/UCSCLibrary/dams_project_mgmt/issues/276).
Note: This pull request doesn't address the resizing of the search results thumbnails.
Changes:
- Stylesheet updates.
- New collections views and partials.
- New kaminari pagination theme files.
- Updates to the hyrax.en.yml localisation file.
Screenshots:
> 176 collection landing page

- Gemfile
- Gemfile.lock
- Jenkinsfile
- config/.coveralls.yml
- spec/spec_helper.rb
- spec/spec_helper_derailed.rb
This pull request should install coverall on our project with its default configuration
> 372 install coverall

- app/views/_controls.html.erb
- app/views/_head_tag_extras.html.erb
- app/views/_logo.html.erb
- app/views/_masthead.html.erb
- app/views/_user_util_links.html.erb
- app/views/catalog/_index_header_gallery_default.html.erb
- app/views/catalog/_index_header_list_default.html.erb
- app/views/catalog/_index_list_default.html.erb
- app/views/catalog/_search_form.html.erb
- app/views/catalog/_search_header.html.erb
- app/views/catalog/_targeted_search_form.html.erb
- app/views/github_credentials/_form.html.erb
- app/views/records/edit_fields/_date.html.erb
- app/views/records/edit_fields/_default.html.erb
- app/views/records/edit_fields/_language.html.erb
- app/views/records/edit_fields/_license.html.erb
- app/views/shared/_ajax_modal.html.erb
- app/views/shared/_footer.html.erb
- app/views/works_mailer/work_link_email.html.erb
- app/views/works_mailer/work_link_email.text.erb
View scripts in the "hyrax" folder have already been annotated. This pull request includes annotations for all the remaining view scripts, which will facilitate future hyrax upgrades.
> added comment headers to remaining view scripts for upgrade purposes

- app/assets/stylesheets/ucsc.scss.erb
- app/controllers/catalog_controller.rb
- app/controllers/collections_controller.rb
- app/indexers/work_indexer.rb
- app/presenters/ucsc/collection_presenter.rb
- app/views/hyrax/collections/_show_collection_with_subcollections.html.erb
- app/views/hyrax/collections/_show_collection_without_subcollections.html.erb
- app/views/hyrax/collections/_subcollection_list.html.erb
- app/views/hyrax/collections/show.html.erb
- app/views/layouts/collection_with_subcollections.html.erb
This implements a separate custom layout and styling for collections that contain subcollections (i.e. "collections of collections" or "collection groups").
> 231 collection of collections page

- app/assets/javascripts/facets.js
- app/assets/stylesheets/ucsc.scss.erb
- app/controllers/catalog_controller.rb
- app/views/catalog/_facets.html.erb
- app/views/catalog/_results_pagination.html.erb
- app/views/catalog/_search_header.html.erb
- app/views/catalog/_search_results.html.erb
- app/views/catalog/_sort_and_per_page.html.erb
- app/views/catalog/index.html.erb
Initial commit and pull request for the search results page overhaul.
> Search results page: Sort and per page widget styling.

- app/presenters/ucsc/collection_presenter.rb
- app/views/hyrax/base/_collection_metadata.html.erb
- app/views/hyrax/collections/_collection_description.html.erb
- app/views/hyrax/collections/_show_collection_with_subcollections.html.erb
- app/views/hyrax/collections/_show_collection_without_subcollections.html.erb
Basic code to display metadataSource as part of collection descriptions. I want to test it out in Staging with real content before finalizing the styling.
> display metadataSource property with collection descriptions

- app/assets/stylesheets/ucsc.scss.erb
- app/views/hyrax/collections/_show_collection_without_subcollections.html.erb
Resolves [420 - Collection Description Box Styling Issues](https://github.com/UCSCLibrary/dams_project_mgmt/issues/420).
Code changes:
- Removes bootstrap classes causing the issues.
- Fixes CSS to implement the correct responsive layout.
> Fix collection description box layout issues.

- Gemfile.lock
Did this one backwards. Merging the Oauth update already applied to production.
> OAuth update

- Gemfile.lock
Reverts UCSCLibrary/ucsc-library-digital-collections#146
> Revert "OAuth update"

- stack_car/.env
Reverts UCSCLibrary/ucsc-library-digital-collections#209
> Revert "ENV variable for image_server"

- app/views/hyrax/collections/show_all.html.erb
This PR to be considered after Notch8 code is successfully pushed to staging.
> fix pagination A-Z list

- Gemfile.lock
- app/models/concerns/bulkrax/metadata.rb
- config/initializers/bulkrax.rb
- db/schema.rb
The majority of the work for this feature is in this Bulkrax PR: https://github.com/samvera-labs/bulkrax/pull/371 
Please refer to [this ticket](https://gitlab.com/notch8/ucsc-library-digital-collections/-/issues/3) for Acceptance Criteria and Testing Instructions
> Add ability to import relationships from child records with bulkrax

- lib/capistrano/tasks/link-stream.rake
> chown bulkrax tmp directories before they're removed

- Gemfile
- Gemfile.lock
Related: https://github.com/UCSCLibrary/dams_project_mgmt/issues/497 
Update bulkrax to v2.2.0
> Collections and FileSets get exported by Bulkrax

- Gemfile
- Gemfile.lock
- db/schema.rb
Ref https://github.com/UCSCLibrary/dams_project_mgmt/issues/500 and https://github.com/UCSCLibrary/dams_project_mgmt/issues/501
> Update Bulkrax to v3.0.0.beta1

- Gemfile
- Gemfile.lock
Ref https://github.com/UCSCLibrary/dams_project_mgmt/issues/512
- Fixes bug when importing collection relationships 
- Changes default export join character from semi-colon to pipe (`|`)
> Update Bulkrax to v3.0.0.beta2

- app/models/file_set.rb
Ref https://github.com/UCSCLibrary/dams_project_mgmt/issues/504
> Only run Kakadu derivatives on TIFF images

- Gemfile
- Gemfile.lock
- db/schema.rb
Fixes failing relationships jobs:
> Update Bulkrax to v3.0.0.beta3

- Gemfile
- Gemfile.lock
Should fix: 
- https://github.com/UCSCLibrary/dams_project_mgmt/issues/522
> update Bulkrax to v3.0.0.beta6

- app/forms/hyrax/forms/collection_form.rb
- app/forms/hyrax/work_form.rb
- app/models/concerns/bulkrax/has_local_processing.rb
- app/models/concerns/hyrax/basic_metadata.rb
- app/views/hyrax/base/_secondary_attribute_rows.html.erb
- app/views/records/edit_fields/_dateOfSituation.erb
- config/initializers/bulkrax.rb
- config/locales/hyrax.en.yml
- config/metadata.yml
- spec/models/concerns/has_local_processing_spec.rb
Ref https://github.com/UCSCLibrary/dams_project_mgmt/issues/517
> i517 Properly handle all date fields when importing

- Gemfile
- Gemfile.lock
https://github.com/samvera-labs/bulkrax/releases/tag/v3.0.0.beta7 
Fixes bug related to https://github.com/UCSCLibrary/dams_project_mgmt/issues/495
> update Bulkrax to v3.0.0.beta7

- app/actors/hyrax/actors/collection_actor.rb
- app/actors/hyrax/actors/work_actor.rb
- app/factories/bulkrax/object_factory.rb
- app/models/concerns/bulkrax/has_local_processing.rb
Ref https://github.com/UCSCLibrary/dams_project_mgmt/issues/521 
Replace value of imported controlled field with all values included on import
This effectively "deletes" values that aren't included in the CSV, e.g. when importing a blank column
> i521 Fix deleting controlled fields when importing

- Gemfile.lock
Related to https://github.com/UCSCLibrary/dams_project_mgmt/issues/518 
Bulkrax v3.1.0 [Release Notes](https://github.com/samvera-labs/bulkrax/releases/tag/v3.1.0)
> i518 update Bulkrax to v3.1.0

- Gemfile.lock
Related: https://github.com/UCSCLibrary/dams_project_mgmt/issues/533 
Bulkrax v3.1.1 [Release Notes](https://github.com/samvera-labs/bulkrax/releases/tag/v3.1.1) 
Bulkrax v3.1.2 [Release Notes](https://github.com/samvera-labs/bulkrax/releases/tag/v3.1.2)
> update Bulkrax to v3.1.2

- Gemfile.lock
- app/jobs/bulkrax/create_relationships_job.rb
- app/jobs/inherit_metadata_job.rb
Reverts UCSCLibrary/ucsc-library-digital-collections#303 and gets the original changes back.
> Revert "Revert "i518 trigger work metadata inheritance after relationships are imported""

- app/models/file_set.rb
- config/initializers/patches.rb
Ref https://github.com/UCSCLibrary/dams_project_mgmt/issues/538 
Co-authored-by: Rob Kaufman <rob@notch8.com>
> Create JP2K derivatives for JPEG files

- app/models/file_set.rb
- config/initializers/patches.rb
Reverts UCSCLibrary/ucsc-library-digital-collections#305
> Revert "Create JP2K derivatives for JPEG files"

- Gemfile.lock
Ref https://github.com/UCSCLibrary/dams_project_mgmt/issues/556 
Update Bulkrax to v3.3.0 ([release notes](https://github.com/samvera-labs/bulkrax/releases/tag/v3.3.0))
> i556 Fix ModelMismatch error when importing FileSets

- Gemfile.lock
- app/jobs/bulkrax/create_relationships_job.rb
- db/schema.rb
Ref https://github.com/UCSCLibrary/dams_project_mgmt/issues/532 
Changes: 
- Update to Bulkrax v3.3.1 ([release notes](https://github.com/samvera-labs/bulkrax/releases/tag/v3.3.1)) 
- Run migrations 
- Update overwritten code to be inline with upstream Bulkrax changes
> i532 destroy pending relationships when destroying failed importers

- db/migrate/20220617180427_re_add_bulkrax_pending_relationships_foreign_key.rb
- db/schema.rb
Ref https://github.com/UCSCLibrary/dams_project_mgmt/issues/532 
Re-add Bulkrax pending relationships foreign key
> i532 Fix build

- bin/remove_relationships
Add script to remove all relationships from imported records
> Remove relationships script

- app/assets/stylesheets/ucsc.scss.erb
Resolves [565](https://github.com/UCSCLibrary/dams_project_mgmt/issues/565). Minor changes to css only: footer no longer fixed, content bottom padding is now 100px instead of 200-400px.
> Footer is no longer fixed.

- app/parsers/bulkrax/application_parser.rb
Fixes https://github.com/UCSCLibrary/dams_project_mgmt/issues/564
> fix csv permission issue for some users

- app/indexers/work_indexer.rb
Resolves this error we see on sandbox currently.
> fix NoMethodErr

- app/indexers/controlled_indexer_behavior.rb
Fix for https://github.com/UCSCLibrary/ucsc-library-digital-collections/issues/421
> fix local authority minting for strings

- config/locales/hyrax.en.yml
Resolves #381 
Changes: Updates the hyrax.en.yml file in /config with the new paragraph, just the last sentence is removed.
> Update language for About Our Collections page

- app/assets/stylesheets/ucsc.scss.erb
Re-applying the CSS fix for #420.
> A-Z thumbnails same height via css.

- spec/indexers/work_indexer_spec.rb
- spec/models/work_spec.rb
Reverts UCSCLibrary/ucsc-library-digital-collections#483
> Revert "bring the tests back"

- app/indexers/controlled_indexer_behavior.rb
Reverts UCSCLibrary/ucsc-library-digital-collections#486
> Revert "do not replace anything for getty urls"

- app/indexers/work_indexer.rb
Resolves https://github.com/UCSCLibrary/ucsc-library-digital-collections/issues/452
> ADD inheritance for collection to works

- app/assets/stylesheets/ucsc.scss.erb
Resolves #525 by using flexbox for the layout instead of floats.
> Use flexbox layout for a-z collections

- config/metadata.yml
Resolves #536 by swapping the definitions of rights statement and rights status.
> Swap definitions for rights status and statement.

- app/indexers/work_indexer.rb
- app/models/work.rb
resolves [544](https://github.com/UCSCLibrary/ucsc-library-digital-collections/issues/544)
> 544 remove duplicate controlled field values

- config/metadata.yml
> remove ADD inheritance for SubjectPlace to QA Aerials

- config/metadata.yml
> 575 remove IR subject place

- app/assets/javascripts/facets.js
> fix facet panel bug

- app/views/hyrax/collections/index.html.erb
Resolves #507 label issue (from QA comments).
> Change results label for a-z to 'collections'

- config/metadata.yml
Resolves #401 by adding dateDigitized to the admin_only display group in metadata.yml.
> 401 date digitized

- app/controllers/collections_controller.rb
- app/views/hyrax/collections/index.html.erb
> modify url to sort works in a collection by title

- app/controllers/collections_controller.rb
> re-order Cabrillo Music festival

- app/helpers/hyrax_helper.rb
- app/views/catalog/_facet_limit.html.erb
> Apply new facet styling: Desktop

- config/metadata.yml
Resolves #392 follow up comment. Keyword and Subject(Time) are no longer facetable.
> remove keyword and subject time facets

- app/views/hyrax/base/_attribute_rows.html.erb
- config/locales/hyrax.en.yml
- config/metadata.yml
> 611 update label

- config/metadata.yml
Resolves #429.
Moves Accession Number into the secondary fields display group, making it visible to all users.
> 429 accession number
